### PR TITLE
Add LBxJournal, VerySpatial.com, and 3D Visualization World as media spo...

### PR DESCRIPTION
**Pull request by elil**
...nsors and another carousel page.  

Does this add another 'page' on the carousel?

### CODE REVIEW

**Comment by mapsam** [comment]
Ouph, sorry I pushed some things before seeing this. I'm lagging on getting the sponsor stuff figured out. I may have to deny this one and then have you add again once I finalize how we're going to structure that carousel. I'm thinking we can randomly grab some sponsors (from specific levels) to push onto the slider when the page is loaded. Maybe the carousel as a whole links to the sponsor page, then, which gives full credit to everyone before you can go to specific sponsors' sites? 

Featured sponsors are a different story, and I'm thinking they can go on the left-hand side where it currently says "Sponsors".

**Comment by mapsam** [comment]
But you totally nailed it, on adding another slide to the carousel, btw!

**Comment by elil** [comment]
Ok, just let me know when/if to do it again.  

I like the idea of all linking to the sponsors page.  I also realized these should probably all have target= so that it opens in a new window.  We don't want people leaving our site.

**Comment by mapsam** [comment]
Eli, these have been added in now. Sorry again for the delay! If you are adding a new sponsor, you can add via the wordpress custom post for "Sponsors"

screen shot 2014-02-19 at 5 41 25 pm

You'll have to add their webpage URL in the meta field

screen shot 2014-02-19 at 5 41 49 pm

associate their sponsorship level

screen shot 2014-02-19 at 5 41 58 pm

and add their logo as the featured image.

screen shot 2014-02-19 at 5 43 39 pm

The title is their name and you can fill out the main content with a description if you feel like it. The descriptions aren't currently used but they could be in the future. 

Cheers,
Sam

**Pull request closed without merging**
